export const EnglishMovies = [
  {
    id: 0,
    movie: "Bob Marley: One Love",
    year: 2024,
    hero: "Kingsley Ben-Adir",
    heroine: "Noomi Rapace",
    director: "Reinaldo Marcus Green",
    image:
      "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQRCpWXmWi_K6wNvkYOxKXxkT1uuOeNDQBXa8T7tGpdBSHr7hq6rgQEnd4lvVYEvq9MDNsdGQ",
  },
  {
    id: 1,
    movie: "It Ends with Us",
    year: 2024,
    hero: "Blake Lively",
    heroine: "Justin Baldoni",
    director: "Justin Baldoni",
    image: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQOuckHAbhp0tDatn4JfCC74fpjpzvxaWaW-gkL46m3p3nXc1kaYOI2oLr5GbMEsfXBr_ji",
  },
  {
    id: 2,
    movie: "The Idea of You",
    year: 2024,
    hero: "Sebastian Stan",
    heroine: "Anne Hathaway",
    director: "Michael Showalter",
    image: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSW90iEHlEkVsdJ2SSswjBnnHMMbQ6ANxjnDuJc-LH2OVOM_UBhFnPcu0GuWwYRPJawFkEM",
  },
  {
    id: 3,
    movie: "Fall Guy",
    year: 2024,
    hero: "Ryan Gosling",
    heroine: "Emily Blunt",
    director: "David Leitch",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTJhBAFnWk-3tBPBLpibGxRs6h0R9QjLTTcWzmel-IcLmvRHvuk2uZrnBX5I4sGm8L0WZ20",
  },
  {
    id: 4,
    movie: "Killer Heat",
    year: 2024,
    hero: "Brad Pitt",
    heroine: "Margot Robbie",
    director: "Quentin Tarantino",
    image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTXTxa50wNp6VdWcH_47ojWviCJ8w0j-FSZw3ecq3P5BQ06dbhVKHnCKBjxlarnWHTbHQrK",
  },
  {
    id: 5,
    movie: "Fly Me to the Moon",
    year: 2024,
    hero: "Tom Hanks",
    heroine: "Cate Blanchett",
    director: "Steven Spielberg",
    image: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS3Aifkmp-plP9RfcAgsK9_IpZESQ8EmVO4Zt_ClLBaHG2mPJNM1HbGR2w4LV9MimVh0AWh1w",
  },
];
